language: go

services:
  - docker

go:
  - "1.9.x"
  - "1.10.x"
  - "1.11.x"
  - "1.12.x"
  - tip

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
  - docker pull i386/golang:1.12-alpine
  - docker run -dit --name test i386/golang:1.12-alpine sh
  - docker exec test sh -c "apk add --no-cache git"
  - docker exec test sh -c "mkdir -p /go/src/github.com/shamaton/msgpack"
  - docker cp ./* test:/go/src/github.com/shamaton/msgpack

script:
  - docker exec test sh -c "cd /go/src/github.com/shamaton/msgpack && go test -v ."
  - $GOPATH/bin/goveralls -service=travis-ci
